import nodemailer from "nodemailer";

export async function sendOfferEmail(
  to: string,
  name: string,
  position: string,
  salary: string = "Competitive"
) {
  const transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST,
    port: Number(process.env.SMTP_PORT),
    secure: false,
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
  });

  const htmlTemplate = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { 
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
      line-height: 1.6; 
      color: #333;
      margin: 0;
      padding: 0;
      background-color: #f4f4f4;
    }
    .container { 
      max-width: 600px; 
      margin: 20px auto; 
      background: white;
      border-radius: 10px;
      overflow: hidden;
      box-shadow: 0 4px 6px rgba(0,0,0,0.1);
    }
    .header { 
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
      color: white; 
      padding: 40px 30px; 
      text-align: center;
    }
    .header h1 {
      margin: 0;
      font-size: 28px;
      font-weight: 600;
    }
    .content { 
      padding: 40px 30px;
    }
    .highlight { 
      background: #f8f9fa;
      border-left: 4px solid #667eea;
      padding: 20px;
      margin: 25px 0;
      border-radius: 5px;
    }
    .highlight h3 {
      margin-top: 0;
      color: #667eea;
      font-size: 18px;
    }
    .detail-row {
      display: flex;
      justify-content: space-between;
      padding: 10px 0;
      border-bottom: 1px solid #e0e0e0;
    }
    .detail-row:last-child {
      border-bottom: none;
    }
    .detail-label {
      font-weight: 600;
      color: #555;
    }
    .detail-value {
      color: #333;
      text-align: right;
    }
    .cta-button {
      display: inline-block;
      background: #667eea;
      color: white;
      padding: 15px 30px;
      text-decoration: none;
      border-radius: 5px;
      margin: 20px 0;
      font-weight: 600;
    }
    .footer { 
      text-align: center; 
      padding: 30px;
      background: #f8f9fa;
      color: #666; 
      font-size: 14px;
    }
    ul {
      padding-left: 20px;
    }
    li {
      margin: 10px 0;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>🎉 Job Offer</h1>
    </div>
    
    <div class="content">
      <p>Dear <strong>${name}</strong>,</p>
      
      <p>We are thrilled to extend a formal offer of employment for the position of <strong>${position}</strong> at our company!</p>
      
      <div class="highlight">
        <h3>📋 Offer Details</h3>
        <div class="detail-row">
          <span class="detail-label">Position:</span>
          <span class="detail-value">${position}</span>
        </div>
        <div class="detail-row">
          <span class="detail-label">Compensation:</span>
          <span class="detail-value">${salary}</span>
        </div>
        <div class="detail-row">
          <span class="detail-label">Start Date:</span>
          <span class="detail-value">As mutually agreed</span>
        </div>
        <div class="detail-row">
          <span class="detail-label">Employment Type:</span>
          <span class="detail-value">Full-time</span>
        </div>
      </div>
      
      <p>We were thoroughly impressed by your qualifications, experience, and the skills you demonstrated during our evaluation process. We believe you would be an excellent addition to our team and are excited about the contributions you will make.</p>
      
      <p><strong>Next Steps:</strong></p>
      <ul>
        <li>Review the full offer letter and employment agreement (attached)</li>
        <li>Sign and return the documents by the specified date</li>
        <li>Complete the onboarding paperwork</li>
        <li>Feel free to reach out with any questions</li>
      </ul>
      
      <center>
        <a href="mailto:${process.env.SMTP_USER}" class="cta-button">Accept Offer</a>
      </center>
      
      <p>We look forward to welcoming you to the team!</p>
      
      <p>Best regards,<br>
      <strong>Hiring Team</strong><br>
      Synapse AI Recruitment</p>
    </div>
    
    <div class="footer">
      <p>This offer is contingent upon successful completion of background checks and reference verification.</p>
      <p>📧 Generated by Synapse Agentic AI System</p>
    </div>
  </div>
</body>
</html>
  `;

  const mailOptions = {
    from: `"Synapse Recruitment" <${process.env.SMTP_USER}>`,
    to: to,
    subject: `Job Offer - ${position} Position`,
    html: htmlTemplate,
  };

  await transporter.sendMail(mailOptions);
  console.log(
    `✉️ Offer email sent to ${to} for ${position} position (${salary})`
  );
}
